### ISSUE TITLE
[MOD]: Voxelmap

### ISSUE THREAD

**Issue by ComradeBlaze** [uku3lig/uklient-java#3]
### Mod Link

https://www.curseforge.com/minecraft/mc-mods/voxelmap

### Info about the mod

mappy map map map THIS MOD SUCKS FUCK VOXELMAP USE XAERO'S fuck hh 

### Additional Info

~~thank you uku ily i will purchase the outfit soon:tm:~~ fuck me these are public

**Comment by uku3lig** [comment]
perfect ty sigma could you rate your experience out of 10

**Comment by ComradeBlaze** [comment]
10/10 dear i love filling out forms

**Comment by uku3lig** [comment]
perfect i will now close this and go to sleep since i already added voxelmap and xaero's

**Comment by ComradeBlaze** [comment]
gn <3
